version: '3'

services:
  dockka.api:
    environment:
      - SQL_CONN=Server=sql,1433;Initial Catalog=dockka;User Id=sa;Password=Test123!
    ports:
      - "8001:80"

  dockka.web:
    ports:
      - "8000:80"

