version: '3.4'

services:
  dockka-api:
    image: dockka-api
    build:
      context: .
      dockerfile: src/Dockka.Api/Dockerfile
    environment:
      - AKKA_CONF_FILENAME=akka.docker.conf
      - SQL_CONN=Server=dockka-sql,1433;Initial Catalog=Dockka;User Id=sa;Password=Test123!
    networks:
      - dockka-network
    depends_on:
      - logstash
      - dockka-sql

  dockka-actorone:
    image: dockka-actorone
    build:
      context: .
      dockerfile: src/Dockka.Actors.ActorOne/Dockerfile
    environment:
      - AKKA_CONF_FILENAME=akka.docker.conf
      - SQL_CONN=Server=dockka-sql,1433;Initial Catalog=Dockka;User Id=sa;Password=Test123!
    networks:
      - dockka-network
    depends_on:
      - dockka-api

  dockka-actortwo:
    image: dockka-actortwo
    build:
      context: .
      dockerfile: src/Dockka.Actors.ActorTwo/Dockerfile
    environment:
      - AKKA_CONF_FILENAME=akka.docker.conf
      - SQL_CONN=Server=dockka-sql,1433;Initial Catalog=Dockka;User Id=sa;Password=Test123!
    networks:
      - dockka-network
    depends_on:
      - dockka-api

  dockka-web:
    image: dockka-web
    build:
      context: .
      dockerfile: src/Dockka.Web/Dockerfile
    
  dockka-sql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test123!
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    networks:
      - dockka-network

  elasticsearch:
    build: 
      context: logging/elasticsearch/
    volumes:
      - ./logging/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - dockka-network

  logstash:
    build: 
      context: logging/logstash/
    volumes:
      - ./logging/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logging/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "2120:2120"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - dockka-network
    depends_on:
      - elasticsearch

  kibana:
    build: 
      context: logging/kibana/
    volumes:
      - ./logging/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - dockka-network
    depends_on:
      - elasticsearch

networks:
  dockka-network:
    driver: bridge
